name: SolarEngineer
options:
  bundleId: com.yourcompany.SolarEngineer
  deploymentTarget: "17.0"

targets:
  SolarEngineer:
    type: application
    platform: iOS
    sources:
      - path: App        # <--- تم تغييرها من SolarEngineerApp.swift إلى App
      - path: Models
      - path: Services
      - path: Views
      - path: Theme
